using WuWaFpsUnlock.Core;

public static class NoticeTests
{
    public static async Task RunAsync(Func<string,Func<Task>,Task> test)
    {
        static void Check(bool value){if(!value)throw new Exception("notice/source assertion failed");}
        await test("notice is pending only after changed successful deployment",()=>{var r=new DeploymentReceipt{Status="Deployed",Notice=new()};DeploymentNoticeStore.CompleteSuccessfulDeployment(r,false);Check(!DeploymentNoticeStore.RequiresAcknowledgement(r));DeploymentNoticeStore.CompleteSuccessfulDeployment(r,true);Check(DeploymentNoticeStore.RequiresAcknowledgement(r));return Task.CompletedTask;});
        await test("notice cancellation is not acknowledgement; same reuse preserves acknowledgement",()=>{var r=new DeploymentReceipt{Status="Deployed",Notice=new()};DeploymentNoticeStore.CompleteSuccessfulDeployment(r,true);Check(DeploymentNoticeStore.RequiresAcknowledgement(r));Check(r.Notice!.AcknowledgedAt is null);DeploymentNoticeStore.Acknowledge(r);long generation=r.Notice.InstallationGeneration;DeploymentNoticeStore.CompleteSuccessfulDeployment(r,false);Check(!DeploymentNoticeStore.RequiresAcknowledgement(r)&&generation==r.Notice.InstallationGeneration);return Task.CompletedTask;});
        await test("notice changes reset per-installation pending",()=>{var r=new DeploymentReceipt{Status="Deployed",Notice=new()};DeploymentNoticeStore.CompleteSuccessfulDeployment(r,true);DeploymentNoticeStore.Acknowledge(r);DeploymentNoticeStore.CompleteSuccessfulDeployment(r,true);Check(r.Notice!.InstallationGeneration==2&&r.Notice.AcknowledgedGeneration==1&&DeploymentNoticeStore.RequiresAcknowledgement(r));return Task.CompletedTask;});
        await test("legacy deployed notice migrates without clearing evidence",()=>{var r=new DeploymentReceipt{Status="Deployed",Files=[new(){Path="evidence"}]};Check(DeploymentNoticeStore.RequiresAcknowledgement(r));DeploymentNoticeStore.InitializeLegacy(r);Check(r.Files.Count==1&&r.Notice!.Pending);DeploymentNoticeStore.Acknowledge(r);Check(!DeploymentNoticeStore.RequiresAcknowledgement(r));return Task.CompletedTask;});
        await test("clean and redeploy archives receipt and resets notice only on actual change",()=>{var r=new DeploymentReceipt{Status="Deployed",Notice=new(),Files=[new(){Path="old file"}],IniEdits=[new(){Key="old key"}]};DeploymentNoticeStore.CompleteSuccessfulDeployment(r,true);DeploymentNoticeStore.Acknowledge(r);r.Status="Cleaned";DeploymentNoticeStore.MarkCleaned(r);var next=DeploymentNoticeStore.BeginAfterClean(r,"root","game");Check(next.History.Count==1&&next.History[0].Files.Count==1&&next.History[0].IniEdits.Count==1&&next.Files.Count==0);next.Status="Deployed";DeploymentNoticeStore.CompleteSuccessfulDeployment(next,true);Check(next.Notice!.InstallationGeneration==2&&DeploymentNoticeStore.RequiresAcknowledgement(next));return Task.CompletedTask;});
        await test("notice acknowledgement persists across JSON restart",()=>{var directory=Path.GetFullPath(Path.Combine("artifacts","notice-test",Guid.NewGuid().ToString("N")));Directory.CreateDirectory(directory);string path=Path.Combine(directory,"receipt.json");var r=new DeploymentReceipt{Status="Deployed",Notice=new()};DeploymentNoticeStore.CompleteSuccessfulDeployment(r,true);JsonFiles.Save(path,r);Check(DeploymentNoticeStore.RequiresAcknowledgement(JsonFiles.Read<DeploymentReceipt>(path)));DeploymentNoticeStore.Acknowledge(r);JsonFiles.Save(path,r);Check(!DeploymentNoticeStore.RequiresAcknowledgement(JsonFiles.Read<DeploymentReceipt>(path)));File.Delete(path);Directory.Delete(directory);return Task.CompletedTask;});
        await test("partial write retained until a successful no-op retry completes notice",()=>{var r=new DeploymentReceipt{Status="PartialFailure",Notice=new(),PendingDeploymentChanges=true};Check(!DeploymentNoticeStore.RequiresAcknowledgement(r));r.Status="Deployed";DeploymentNoticeStore.CompleteSuccessfulDeployment(r,false);Check(DeploymentNoticeStore.RequiresAcknowledgement(r)&&!r.PendingDeploymentChanges);DeploymentNoticeStore.Acknowledge(r);DeploymentNoticeStore.CompleteSuccessfulDeployment(r,false);Check(!DeploymentNoticeStore.RequiresAcknowledgement(r));return Task.CompletedTask;});
        foreach(var source in new[]{"ToolInstalled","UserExisting","LegacyUnknown"})
            await test("ReShade cleanup provenance "+source,async()=>{var dir=Path.GetFullPath(Path.Combine("artifacts","notice-test",Guid.NewGuid().ToString("N")));Directory.CreateDirectory(dir);string proxy=Path.Combine(dir,"dxgi.dll");File.WriteAllText(proxy,"inert runtime fixture");var r=new DeploymentReceipt{GameRoot=dir,GameExe=Path.Combine(dir,"Client-Win64-Shipping.exe"),ProxyPath=proxy,Files=[new(){Path=proxy,Kind="ReShade",CreatedByTool=true,Completed=true,SourceKind=source,SourcePath="provided-setup.exe",SourceHash=new string('a',64),InstalledHash=await SafePaths.HashAsync(proxy)}]};Check(ReShadeOwnership.CanClean(r,r.Files[0])==(source=="ToolInstalled"));await DeploymentFiles.CleanOwnedAddonsAsync(r,()=>{},_=>{});Check(File.Exists(proxy)!=(source=="ToolInstalled"));if(File.Exists(proxy))File.Delete(proxy);Directory.Delete(dir);});
        await test("ReShade ownership refuses another load directory",()=>{var root=Path.GetFullPath(Path.Combine("artifacts","notice-test"));var proxy=Path.Combine(root,"other","dxgi.dll");var r=new DeploymentReceipt{GameRoot=root,GameExe=Path.Combine(root,"Client-Win64-Shipping.exe"),ProxyPath=proxy};Check(!ReShadeOwnership.CanClean(r,new(){Path=proxy,Kind="ReShade",CreatedByTool=true,Completed=true,SourceKind="ToolInstalled",SourcePath="setup.exe",SourceHash=new string('a',64)}));return Task.CompletedTask;});
    }
}
